# -*- coding: cp1252 -*-
import nltk
import re
sentence="""Una de las clases que más adeptos tiene en los gimnasios suele ser la de stretching o estiramientos, y es que estirar nuestros músculos es importante y beneficioso después de realizar cualquier actividad físicaLas sesiones específicas de stretching suelen durar entre 20 y 30 minutos, tiempo suficiente para estirar los músculos implicados en el deporte que acabamos de practicar. ¿Cuáles son las tres reglas de oro de los estiramientos? La primera regla, y posiblemente la más importante, es que durante nuestros estiramientos no debemos sentir dolor: solamente debemos notar resistencia. El dolor es un mecanismo de aviso de nuestro sistema nervioso para comunicarnos que se puede producir una lesión, y esto es precisamente lo que estamos tratando de evitar a través de los estiramientos.Bien es cierto que hay personas que escudándose en la idea de no sentir dolor no realizan los ejercicios de estiramiento correctamente: debemos sentir una tensión moderada en el músculo que estamos estirando para que los estiramientos sean efectivos.La segunda regla del stretching es que los estiramientos deben ser mantenidos en el tiempo durante aproximadamente 20 o 30 segundos. Debemos estirar el músculo concreto y mantener esa tensión moderada durante un período corto de tiempo para después volver a relajarlo.Es importante que no realicemos movimientos balísticos (tirones rápidos para llegar a la máxima elongación del músculo), ya que pueden provocar dolor o lesiones en el músculo. Los estiramientos balísticos son uno de los método utilizados para trabajar la flexibilidad, aunque se les achaca que debido al tiempo reducido de estiramiento no existe una adaptación neuromuscular.Personalmente, en las sesiones colectivas de stretching prefiero trabajar con movimientos controlados y mantenidos en el tiempo, que son más seguros y, a mi parecer, más efectivos para la población media de los gimnasios.No podemos olvidar la correcta alineación corporal y corrección postural durante los estiramientos. Mantener una postura correcta, por ejemplo, durante un ejercicio de articulación de la columna, es vital para prevenir lesiones y sacar el máximo partido a nuestras sesiones de estiramientos.Las pautas suelen ser similares en todos los ejercicios: hombros atrás y abajo, cintura escapular alineada, mirada al frente, pecho arriba, pelvis neutra… Son datos que debemos conocer y que el instructor debe transmitir a sus alumnos para llevar a cabo estiramientos seguros y efectivos.Y vosotros, ¿estiráis siempre al acabar vuestro entrenamiento?"""
text = nltk.word_tokenize(sentence)
tagged=nltk.pos_tag(text)
namedentities = nltk.chunk.ne_chunk(tagged,binary=True)
entities=re.findall(r'NE\s(.*?)/',str(namedentities))
print(entities)
